apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: my-ghcr-secret
      containers:
      - name: frontend
        image: ghcr.io/alchemist006/bc-125-demo/bc-125-checkr-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "development"
        - name: API_URL
          value: "https://api.example.com"
        - name: AUTH0_DOMAIN
          value: "dev-yooqx6o4.us.auth0.com"
        - name: AUTH0_CLIENT_ID
          value: "AyXwfgXGAFbgCIX03w4Z1CptEqCE3bxp"
