server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: CANDIDATE-SERVICE
          uri: lb://CANDIDATE-SERVICE
          predicates:
            - Path=/api/v1/candidates/**
        - id: COURTSEARCHES-SERVICE
          uri: lb://COURTSEARCHES-SERVICE
          predicates:
            - Path=/api/v1/court-searches/**
        - id: ADVERSEACTION-SERVICE
          uri: lb://ADVERSEACTION-SERVICE
          predicates:
            - Path=/api/v1/adverse-actions/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
